---
title: "Forschungsorientierte Praktikum I – Grundlagen der Forschung (BSc Psychologie, LMU)"
subtitle: "Robust Evidence: A Workflow for Reproducible, Collaborative, and Transparent Research"
toc: false
---

# Robust Evidence: A Workflow for Reproducible, Collaborative, and Transparent Research

*Note: This project is a mixture of English and German text. Sorry for that.*

This course is held in the 2nd semester of the BSc. Psychology at the [Department Psychology, Ludwig-Maximilians-Universität München](https://lmu.de/psy). See the [Sessions](sessions/sessions_overview.qmd) section for a description of each session. In these sessions, sometimes [lecture slides](slides/slides_overview.qmd) are linked.


## Course Announcement

The focus of this empirical psychology research practicum is less on a specific subject area but more on acquiring solid research methodology, both conceptually and practically. The aim is to develop professional and efficient working practices that will support you throughout your studies and beyond.

You will learn key tools and standards of scientific work, including:

* File versioning and collaborative work with Git
* Reproducible notebooks and manuscripts using Quarto
* Best practices in data analysis (folder structure, code commenting, reflective use and integration of AI)
* Strategies for systematic error prevention

In the area of research methods, you will gain knowledge in:

* Preregistration of hypotheses and analysis plans
* Preparing data for scientific publication (“Open Data”; anonymization, documentation using a codebook)
* Reproducible statistical analysis in R, ensuring results are fully traceable for others
* Sample size planning to ensure sufficiently strong evidence for or against a hypothesis

In terms of content, we will join a global replication project (CREP; [https://www.crep-psych.org](https://www.crep-psych.org)) and participate in a “ManyLabs” study. As one of several sites, we will replicate an existing experiment; our data will then be incorporated into a cross-site meta-analysis. Data collection will take place as a joint online study conducted by the entire group.

This research practicum places higher demands on mathematical and formal thinking as well as on your programming skills. At minimum, knowledge of R as taught in Statistics I and II is required. In addition, a willingness is expected to independently work through more advanced programming content using the provided materials.
