---
title: "Instructions before course"
toc: false
date: 2026-04-13
description: "Some instructions for students before the course starts"
---

Betreff: **Instruktionen Empra**

Liebe Studierende,

ich freue mich schon auf unser Empra. Hier kommen einige Hinweise für den Start am Freitag:

1. Ich würde gerne den Start von 10:15 auf 10:00 verlegen. Die Sitzung geht dann in der Regel bis 13:00, so dass man noch sinnvoll in die Mensa gehen kann. Wir starten also am Freitag gleich um 10:00!

2. Wir werden in fast jeder Sitzung am Computer arbeiten - z.B. Code schreiben, Diagramme zeichnen, oder Dateien in git einchecken. Daher wäre es gut, wenn Sie, wenn möglich, immer ihren Laptop mitbringen. Wenn Sie keinen Laptop haben, können Sie auch bei Kommilitonen reinschauen und im "pair programming" Modus arbeiten.

3. Sie haben ja im Seminar von Statistik 1 schon einige Kenntnisse in R erworben. Ich gehe davon aus, dass Sie diese Kenntnisse mitbringen, wir werden sie hier nicht noch einmal wiederholen. Falls Sie Ihre R-Kenntnisse auffrischen möchten, finden Sie hier einige Ressourcen. Das bedeutet nicht, dass Sie all diese Ressourcen durcharbeiten müssen. Wenn Sie auf dem Stand der beiden R-Tutorials (siehe 3.1) sind, sind Sie hinreichend vorbereitet:
    1. Die R-Tutorials aus Statistik 1: [Teil 1 - Grundlagen](https://www.oer.psy.lmu.de/R_Tutorial/Teil1.html) und [Teil 2 - Workflows bei der Arbeit mit Datensätzen](https://www.oer.psy.lmu.de/R_Tutorial/Teil2.html)
    2. [Moodle Kurs "R Tutorials"](https://moodle.lmu.de/course/view.php?id=12232): Am Lehrstuhl Sozialpsychologie wurden R-Tutorials (Skript englisch, begleitende Videos deutsch) erstellt. Die Tutorials helfen, einen Anfang in R zu finden und zeigen die Durchführung ein paar üblicher Schritte der Datenaufbereitung und -auswertung. Passwort für den Moodle-Kurs: allyouneedisR
    3. YouTube-Video: ["Want to learn R (#rstats) in 4 hours with NO programming experience?"](https://www.youtube.com/playlist?list=PLmNgrNF3pZqg2GPmcIAWDa1A2-cAfbX37)
    4. <https://cran.r-project.org/doc/contrib/Torfs+Brauer-Short-R-Intro.pdf> (12 page PDF document)
    5. <https://github.com/jobreu/r-intro-gesis-2021> (5 day course: slides & exercises)

    

4. Die Kommunikation wird ab jetzt über den [Moodle-Kurs](https://moodle.lmu.de/course/view.php?id=44759) laufen. Der Einschreibeschlüssel lautet: "replikation". Bitte schreiben Sie sich zeitnah ein; ich verschicke ab jetzt die Emails über den Moodle-Kurs.

5. Das Kursmaterial wird sich alles auf Github finden: [https://nicebread.github.io/Empra1_2026/](https://nicebread.github.io/Empra1_2026/). 

Dann sehen wir uns am **Freitag, 17.04.26, um 10:00 in Raum 2301** zur ersten Sitzung! Bei Fragen können Sie sich gerne auch vorab schon bei mir melden.

Viele Grüße,
Felix Schönbrodt
